# HELK script: HELK KSQL CLI Dockerfile
# HELK build Stage: Alpha
# Author: Ignace De Cock (@Krapgras)
# License: GPL-3.0

FROM confluentinc/cp-ksqldb-cli
LABEL maintainer="confluentinc"
LABEL description="Dockerfile base for the HELK KSQL CLI."