# HELK script: HELK KSQL Server Dockerfile
# HELK build Stage: Alpha
# Author: Ignace De Cock (@Krapgras)
# License: GPL-3.0

FROM confluentinc/cp-ksqldb-server
LABEL maintainer="confluentinc"
LABEL description="Dockerfile base for the HELK KSQL Server."